[versions]
agp = "8.10.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"

[libraries]
appcompat = "androidx.appcompat:appcompat:1.6.1"
material = "com.google.android.material:material:1.9.0"

camerax-core = "androidx.camera:camera-core:1.3.1"
camerax-camera2 = "androidx.camera:camera-camera2:1.3.1"
camerax-lifecycle = "androidx.camera:camera-lifecycle:1.3.1"
camerax-view = "androidx.camera:camera-view:1.3.1"

tensorflow-lite = "org.tensorflow:tensorflow-lite:2.14.0"
tensorflow-support = "org.tensorflow:tensorflow-lite-support:0.4.3"

junit = "junit:junit:4.13.2"
androidx-junit = "androidx.test.ext:junit:1.1.5"
espresso-core = "androidx.test.espresso:espresso-core:3.5.1"


